<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $skills = [
            // Programming Languages
            ['name' => 'PHP', 'type' => 'Programming Language'],
            ['name' => 'JavaScript', 'type' => 'Programming Language'],
            ['name' => 'Python', 'type' => 'Programming Language'],
            ['name' => 'Java', 'type' => 'Programming Language'],
            ['name' => 'C++', 'type' => 'Programming Language'],
            ['name' => 'C#', 'type' => 'Programming Language'],
            ['name' => 'Ruby', 'type' => 'Programming Language'],
            ['name' => 'Go', 'type' => 'Programming Language'],
            ['name' => 'Swift', 'type' => 'Programming Language'],
            ['name' => 'Kotlin', 'type' => 'Programming Language'],
            ['name' => 'Objective-C', 'type' => 'Programming Language'],
            ['name' => 'R', 'type' => 'Programming Language'],
            ['name' => 'Scala', 'type' => 'Programming Language'],
            ['name' => 'Perl', 'type' => 'Programming Language'],
            ['name' => 'Rust', 'type' => 'Programming Language'],
            ['name' => 'TypeScript', 'type' => 'Programming Language'],
            ['name' => 'Dart', 'type' => 'Programming Language'],
            ['name' => 'Haskell', 'type' => 'Programming Language'],
            ['name' => 'Elixir', 'type' => 'Programming Language'],
            ['name' => 'Clojure', 'type' => 'Programming Language'],
            ['name' => 'F#', 'type' => 'Programming Language'],
            ['name' => 'Lua', 'type' => 'Programming Language'],
            ['name' => 'Matlab', 'type' => 'Programming Language'],
            ['name' => 'SAS', 'type' => 'Programming Language'],
            ['name' => 'Shell', 'type' => 'Programming Language'],
            ['name' => 'PowerShell', 'type' => 'Programming Language'],
            ['name' => 'VBScript', 'type' => 'Programming Language'],
            ['name' => 'COBOL', 'type' => 'Programming Language'],
            ['name' => 'Fortran', 'type' => 'Programming Language'],
            ['name' => 'Ada', 'type' => 'Programming Language'],
            ['name' => 'Pascal', 'type' => 'Programming Language'],
            ['name' => 'Prolog', 'type' => 'Programming Language'],
            ['name' => 'Lisp', 'type' => 'Programming Language'],
            ['name' => 'Erlang', 'type' => 'Programming Language'],
            ['name' => 'Groovy', 'type' => 'Programming Language'],
            ['name' => 'Crystal', 'type' => 'Programming Language'],
            ['name' => 'Nim', 'type' => 'Programming Language'],
            ['name' => 'Elm', 'type' => 'Programming Language'],
            ['name' => 'OCaml', 'type' => 'Programming Language'],
            ['name' => 'Smalltalk', 'type' => 'Programming Language'],
            ['name' => 'Scheme', 'type' => 'Programming Language'],
            ['name' => 'Forth', 'type' => 'Programming Language'],
            ['name' => 'VHDL', 'type' => 'Programming Language'],
            ['name' => 'Verilog', 'type' => 'Programming Language'],
            ['name' => 'ABAP', 'type' => 'Programming Language'],
            ['name' => 'LabVIEW', 'type' => 'Programming Language'],
            ['name' => 'RPG', 'type' => 'Programming Language'],
            ['name' => 'AWK', 'type' => 'Programming Language'],
            ['name' => 'BCPL', 'type' => 'Programming Language'],
            ['name' => 'D', 'type' => 'Programming Language'],
            ['name' => 'Eiffel', 'type' => 'Programming Language'],
            ['name' => 'Icon', 'type' => 'Programming Language'],
            ['name' => 'IDL', 'type' => 'Programming Language'],
            ['name' => 'J', 'type' => 'Programming Language'],
            ['name' => 'ML', 'type' => 'Programming Language'],
            ['name' => 'Mercury', 'type' => 'Programming Language'],
            ['name' => 'Modula-2', 'type' => 'Programming Language'],
            ['name' => 'Simula', 'type' => 'Programming Language'],
            ['name' => 'SNOBOL', 'type' => 'Programming Language'],
            ['name' => 'SPARK', 'type' => 'Programming Language'],
            ['name' => 'Tcl', 'type' => 'Programming Language'],
            ['name' => 'APL', 'type' => 'Programming Language'],

            // Frameworks
            ['name' => 'Laravel', 'type' => 'Framework'],
            ['name' => 'Symfony', 'type' => 'Framework'],
            ['name' => 'CodeIgniter', 'type' => 'Framework'],
            ['name' => 'CakePHP', 'type' => 'Framework'],
            ['name' => 'Zend Framework', 'type' => 'Framework'],
            ['name' => 'Yii', 'type' => 'Framework'],
            ['name' => 'Slim', 'type' => 'Framework'],
            ['name' => 'Phalcon', 'type' => 'Framework'],
            ['name' => 'FuelPHP', 'type' => 'Framework'],
            ['name' => 'Aura', 'type' => 'Framework'],
            ['name' => 'React', 'type' => 'Framework'],
            ['name' => 'Angular', 'type' => 'Framework'],
            ['name' => 'Vue.js', 'type' => 'Framework'],
            ['name' => 'Ember.js', 'type' => 'Framework'],
            ['name' => 'Backbone.js', 'type' => 'Framework'],
            ['name' => 'Meteor', 'type' => 'Framework'],
            ['name' => 'Svelte', 'type' => 'Framework'],
            ['name' => 'Express', 'type' => 'Framework'],
            ['name' => 'NestJS', 'type' => 'Framework'],
            ['name' => 'Next.js', 'type' => 'Framework'],
            ['name' => 'Nuxt.js', 'type' => 'Framework'],
            ['name' => 'Spring', 'type' => 'Framework'],
            ['name' => 'Struts', 'type' => 'Framework'],
            ['name' => 'Grails', 'type' => 'Framework'],
            ['name' => 'Play', 'type' => 'Framework'],
            ['name' => 'Dropwizard', 'type' => 'Framework'],
            ['name' => 'Micronaut', 'type' => 'Framework'],
            ['name' => 'Django', 'type' => 'Framework'],
            ['name' => 'Flask', 'type' => 'Framework'],
            ['name' => 'Pyramid', 'type' => 'Framework'],
            ['name' => 'Web2py', 'type' => 'Framework'],
            ['name' => 'Tornado', 'type' => 'Framework'],
            ['name' => 'Falcon', 'type' => 'Framework'],
            ['name' => 'Bottle', 'type' => 'Framework'],
            ['name' => 'TurboGears', 'type' => 'Framework'],
            ['name' => 'FastAPI', 'type' => 'Framework'],
            ['name' => 'Ruby on Rails', 'type' => 'Framework'],
            ['name' => 'Sinatra', 'type' => 'Framework'],
            ['name' => 'Hanami', 'type' => 'Framework'],
            ['name' => 'Padrino', 'type' => 'Framework'],
            ['name' => 'ASP.NET', 'type' => 'Framework'],
            ['name' => 'Blazor', 'type' => 'Framework'],
            ['name' => 'Nancy', 'type' => 'Framework'],
            ['name' => 'Mojolicious', 'type' => 'Framework'],
            ['name' => 'Catalyst', 'type' => 'Framework'],
            ['name' => 'Phoenix', 'type' => 'Framework'],
            ['name' => 'Actix', 'type' => 'Framework'],
            ['name' => 'Rocket', 'type' => 'Framework'],

            // Technical Skills
            ['name' => 'Database Management', 'type' => 'Technical Skill'],
            ['name' => 'Version Control', 'type' => 'Technical Skill'],
            ['name' => 'DevOps', 'type' => 'Technical Skill'],
            ['name' => 'Cloud Computing', 'type' => 'Technical Skill'],
            ['name' => 'Cyber Security', 'type' => 'Technical Skill'],
            ['name' => 'Networking', 'type' => 'Technical Skill'],
            ['name' => 'Data Analysis', 'type' => 'Technical Skill'],
            ['name' => 'Data Visualization', 'type' => 'Technical Skill'],
            ['name' => 'Machine Learning', 'type' => 'Technical Skill'],
            ['name' => 'Artificial Intelligence', 'type' => 'Technical Skill'],
            ['name' => 'Software Testing', 'type' => 'Technical Skill'],
            ['name' => 'Agile Methodologies', 'type' => 'Technical Skill'],
            ['name' => 'Scrum', 'type' => 'Technical Skill'],
            ['name' => 'Project Management', 'type' => 'Technical Skill'],
            ['name' => 'UI/UX Design', 'type' => 'Technical Skill'],
            ['name' => 'Mobile Development', 'type' => 'Technical Skill'],
            ['name' => 'Web Development', 'type' => 'Technical Skill'],
            ['name' => 'Game Development', 'type' => 'Technical Skill'],
            ['name' => 'Embedded Systems', 'type' => 'Technical Skill'],
            ['name' => 'Robotics', 'type' => 'Technical Skill'],
            ['name' => 'Big Data', 'type' => 'Technical Skill'],
            ['name' => 'Internet of Things (IoT)', 'type' => 'Technical Skill'],
            ['name' => 'Blockchain', 'type' => 'Technical Skill'],
            ['name' => 'AR/VR', 'type' => 'Technical Skill'],
        ];

        DB::table('skills')->insert($skills);
    }
}
