<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SkillsTableSeeder3 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $skills = [
            // Development Tools and IDEs
            ['name' => 'Git', 'type' => 'Dev Tool'],
            ['name' => 'GitHub', 'type' => 'Dev Tool'],
            ['name' => 'GitLab', 'type' => 'Dev Tool'],
            ['name' => 'Bitbucket', 'type' => 'Dev Tool'],
            ['name' => 'Jira', 'type' => 'Dev Tool'],
            ['name' => 'Trello', 'type' => 'Dev Tool'],
            ['name' => 'VS Code', 'type' => 'IDE'],
            ['name' => 'Atom', 'type' => 'IDE'],
            ['name' => 'Sublime Text', 'type' => 'IDE'],
            ['name' => 'PHPStorm', 'type' => 'IDE'],
            ['name' => 'WebStorm', 'type' => 'IDE'],
            ['name' => 'Eclipse', 'type' => 'IDE'],
            ['name' => 'NetBeans', 'type' => 'IDE'],
            ['name' => 'IntelliJ IDEA', 'type' => 'IDE'],
            ['name' => 'Visual Studio', 'type' => 'IDE'],
            ['name' => 'Android Studio', 'type' => 'IDE'],
            ['name' => 'Xcode', 'type' => 'IDE'],
            ['name' => 'PyCharm', 'type' => 'IDE'],
            ['name' => 'Rider', 'type' => 'IDE'],
            ['name' => 'CLion', 'type' => 'IDE'],
            ['name' => 'DataGrip', 'type' => 'IDE'],
            ['name' => 'RubyMine', 'type' => 'IDE'],
            ['name' => 'AppCode', 'type' => 'IDE'],
            ['name' => 'GoLand', 'type' => 'IDE'],
            ['name' => 'PhpStorm', 'type' => 'IDE'],
            ['name' => 'Coda', 'type' => 'IDE'],
            ['name' => 'TextMate', 'type' => 'IDE'],
            ['name' => 'Vim', 'type' => 'IDE'],
            ['name' => 'Emacs', 'type' => 'IDE'],
            ['name' => 'Notepad++', 'type' => 'IDE'],
            ['name' => 'GNU Emacs', 'type' => 'IDE'],
            ['name' => 'Code::Blocks', 'type' => 'IDE'],
            ['name' => 'CodeLite', 'type' => 'IDE'],
            ['name' => 'Komodo IDE', 'type' => 'IDE'],
            ['name' => 'Aptana Studio', 'type' => 'IDE'],
            ['name' => 'BlueJ', 'type' => 'IDE'],
            ['name' => 'Arduino IDE', 'type' => 'IDE'],
            ['name' => 'Anjuta', 'type' => 'IDE'],
            ['name' => 'KDevelop', 'type' => 'IDE'],
            ['name' => 'MonoDevelop', 'type' => 'IDE'],
            ['name' => 'Eric Python IDE', 'type' => 'IDE'],
            ['name' => 'RStudio', 'type' => 'IDE'],
            ['name' => 'Qt Creator', 'type' => 'IDE'],
            ['name' => 'PyScripter', 'type' => 'IDE'],
            ['name' => 'Geany', 'type' => 'IDE'],
            ['name' => 'Light Table', 'type' => 'IDE'],
            ['name' => 'SharpDevelop', 'type' => 'IDE'],
            ['name' => 'Zend Studio', 'type' => 'IDE'],
            ['name' => 'Wing Python IDE', 'type' => 'IDE'],
            ['name' => 'SlickEdit', 'type' => 'IDE'],
            ['name' => 'Lazarus', 'type' => 'IDE'],
            ['name' => 'DrJava', 'type' => 'IDE'],
            ['name' => 'JCreator', 'type' => 'IDE'],
            ['name' => 'GNU Compiler Collection (GCC)', 'type' => 'Dev Tool'],
            ['name' => 'XAMPP', 'type' => 'Dev Tool'],
            ['name' => 'WampServer', 'type' => 'Dev Tool'],
            ['name' => 'MAMP', 'type' => 'Dev Tool'],
            ['name' => 'Composer', 'type' => 'Dev Tool'],
            ['name' => 'npm', 'type' => 'Dev Tool'],
            ['name' => 'Yarn', 'type' => 'Dev Tool'],
            ['name' => 'Bundler', 'type' => 'Dev Tool'],
            ['name' => 'Pip', 'type' => 'Dev Tool'],
            ['name' => 'Docker', 'type' => 'Dev Tool'],
            ['name' => 'Vagrant', 'type' => 'Dev Tool'],
            ['name' => 'VirtualBox', 'type' => 'Dev Tool'],
            ['name' => 'Kubernetes', 'type' => 'Dev Tool'],
            ['name' => 'Terraform', 'type' => 'Dev Tool'],
            ['name' => 'Ansible', 'type' => 'Dev Tool'],
            ['name' => 'Chef', 'type' => 'Dev Tool'],
            ['name' => 'Puppet', 'type' => 'Dev Tool'],
            ['name' => 'Jenkins', 'type' => 'Dev Tool'],
            ['name' => 'Travis CI', 'type' => 'Dev Tool'],
            ['name' => 'CircleCI', 'type' => 'Dev Tool'],
            ['name' => 'TeamCity', 'type' => 'Dev Tool'],
            ['name' => 'SonarQube', 'type' => 'Dev Tool'],
            ['name' => 'SonarCloud', 'type' => 'Dev Tool'],
            ['name' => 'Coverity', 'type' => 'Dev Tool'],
            ['name' => 'Splunk', 'type' => 'Dev Tool'],
            ['name' => 'Grafana', 'type' => 'Dev Tool'],
            ['name' => 'Prometheus', 'type' => 'Dev Tool'],
            ['name' => 'ELK Stack', 'type' => 'Dev Tool'],
            ['name' => 'Postman', 'type' => 'Dev Tool'],
            ['name' => 'Insomnia', 'type' => 'Dev Tool'],
            ['name' => 'Fiddler', 'type' => 'Dev Tool'],
            ['name' => 'Swagger', 'type' => 'Dev Tool'],
            ['name' => 'Restlet', 'type' => 'Dev Tool'],
            ['name' => 'SoapUI', 'type' => 'Dev Tool'],
            ['name' => 'Pencil', 'type' => 'Dev Tool'],
            ['name' => 'Balsamiq', 'type' => 'Dev Tool'],
            ['name' => 'Axure RP', 'type' => 'Dev Tool'],
            ['name' => 'Sketch', 'type' => 'Dev Tool'],
            ['name' => 'InVision', 'type' => 'Dev Tool'],
            ['name' => 'Figma', 'type' => 'Dev Tool'],
            ['name' => 'Zeplin', 'type' => 'Dev Tool'],
            ['name' => 'Marvel', 'type' => 'Dev Tool'],
            ['name' => 'Framer', 'type' => 'Dev Tool'],
            ['name' => 'Abstract', 'type' => 'Dev Tool'],
            ['name' => 'Avocode', 'type' => 'Dev Tool'],
            ['name' => 'Quixy', 'type' => 'Dev Tool'],
            ['name' => 'OutSystems', 'type' => 'Dev Tool'],
            ['name' => 'Mendix', 'type' => 'Dev Tool'],
            ['name' => 'Betty Blocks', 'type' => 'Dev Tool'],
            ['name' => 'Appian', 'type' => 'Dev Tool'],
            ['name' => 'Salesforce Lightning', 'type' => 'Dev Tool'],
            ['name' => 'Microsoft PowerApps', 'type' => 'Dev Tool'],
            ['name' => 'Retool', 'type' => 'Dev Tool'],
            ['name' => 'Mendix Studio', 'type' => 'Dev Tool'],
        ];

        DB::table('skills')->insert($skills);
    }
}
